#!/bin/bash


# Mac only
if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "This script is designed for macOS."
  exit 1
fi

# Usage
if [[ "$1" == "-h" || "$1" == "--help" || -z "$1" ]]; then
  echo "Usage: $0 /path/to/application.app"
  echo "Checks if an application is from the Mac App Store and if it is VPP-enabled."
  exit 0
fi

# main function loop
for app in "$@"; do
  (
    AppName=$(basename "$app" | sed 's/.app//g')
      
    if [ -f "$app/Contents/_MASReceipt/receipt" ]; then
      if [[ $(openssl asn1parse -inform der -in "$app/Contents/_MASReceipt/receipt" | grep -m 1 'OCTET STRING' | cut -d: -f4 | xxd -r -p | openssl asn1parse -inform der | grep ':15$') ]]; then
        echo "$AppName, you down with VPP?"
        echo "YEA YOU KNOW ME!"
        echo ""
      else
        echo "$AppName, you down with VPP?"
        echo "No. $AppName was manually downloaded from the App Store."
        echo ""
      fi
    else
      echo "$AppName, you down with VPP?"
      echo "No. $AppName does not appear to be a Mac App Store application."
      echo ""
    fi
  )
done
  
exit 0