#!/bin/bash

# Much credit to Per Olofsson https://github.com/MagerValp/
# Inspiration from http://magervalp.github.io/2013/03/19/poking-around-in-masreceipts.html
# Additional references from the Apple Developer documentation on receipts https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW1
# Also credit to Naughty By Nature https://www.youtube.com/watch?v=idx3GSL2KWs

# Mac only
if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "This script is designed for macOS."
  exit 1
fi

# Usage
if [[ "$1" == "-h" || "$1" == "--help" || -z "$1" ]]; then
  echo "Usage: $0 /path/to/application.app"
  echo "Checks if an application is from the Mac App Store and if it is VPP-enabled."
  exit 0
fi

# main function loop
for app in "$@"; do
  (
    AppName=$(basename "$app" | sed 's/.app//g')
    # ********************************************************************************************    
    # This is a very cursory receipt check. It's plausible that it doesn't handle "adoptable 
    # apps" (i.e. the pre-installed, but App Store-updatable). App bundles like Keynote, 
    # Pages, and Numbers are examples on a standard new Mac. It's possible that 
    # configure-to-order "pro" applications available for purchase on new Macs such as 
    # Final Cut Pro and Logic Pro are also using the adoptable state. More testing needed.
    # ********************************************************************************************    
    
    # ********************************************************************************************    
    # Note to future self, it appears that iPhone and iPad apps running on Apple Silicon have 
    # information available in "$app/Wrapper/iTunesMetadata.plist" with keys outlining various
    # download mechanisms for the app. e.g. sideLoadedDeviceBasedVPP, DeviceBasedVPP, and  
    # isB2BCustomApp. Though suspiciously in one example manually-downloaded app that was  
    # previously purchased, the "is-purchased-redownload" key is false. More research is needed.
    # ********************************************************************************************
      
    if [ -f "$app/Contents/_MASReceipt/receipt" ]; then
      if [[ $(openssl asn1parse -inform der -in "$app/Contents/_MASReceipt/receipt" | grep -m 1 'OCTET STRING' | cut -d: -f4 | xxd -r -p | openssl asn1parse -inform der | grep ':15$') ]]; then
        echo "$AppName, you down with VPP?"
        echo "YEA YOU KNOW ME!"
        echo ""
      else
        echo "$AppName, you down with VPP?"
        echo "No. $AppName was manually downloaded from the App Store."
        echo ""
      fi
    else
      echo "$AppName, you down with VPP?"
      echo "No. $AppName does not appear to be a Mac App Store application."
      echo ""
    fi
  )
done
  
exit 0